# Generated by Django 5.2.5 on 2025-08-20 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveBigIntegerField()),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('STOCK_OUT', 'Stock Out'), ('NOT_AVAILABLE', 'Not Available')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, choices=[('SMALL', 'S'), ('MEDIUM', 'M'), ('LARGE', 'L'), ('XTRA_LARGE', 'XL'), ('DOUBLE_EXTRA_LARGE', 'XXL')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
        ),
    ]
