# Generated by Django 5.2.5 on 2025-08-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productimage_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
    ]
